version: '3.8'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    image: summarizer:latest
    container_name: summaries-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=prod
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    container_name: summaries-db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
